### ISSUE TITLE
AC refinement

### ISSUE THREAD

**Issue by jonathanventura** [danini/affine-correspondences-for-camera-geometry#3]
Hello,
Thanks for sharing your code.  Does this repository contain the code for affine correspondence refinement ("least squares matching") described in the paper?  I couldn't find it but maybe I wasn't looking in the right place.
Thanks,
Jonathan

**Comment by danini** [comment]
Hi,
Yeah, that is a future plan to put it into the public code.
You can find the implementation here: https://www.ipb.uni-bonn.de/symmetric-least-squares-matching/
I hope it helps.

Best,
Daniel

**Comment by jonathanventura** [comment]
Thanks!
